/*
Navicat MySQL Data Transfer

Source Server         : local-mysql
Source Server Version : 50709
Source Host           : localhost:3306
Source Database       : blog

Target Server Type    : MYSQL
Target Server Version : 50709
File Encoding         : 65001

Date: 2016-06-28 22:24:39
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for wg_article
-- ----------------------------
DROP TABLE IF EXISTS `wg_article`;
CREATE TABLE `wg_article` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `content` text,
  `created_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `tag` int(5) DEFAULT NULL COMMENT '标签，后续可以添加',
  `tag_des` varchar(255) DEFAULT NULL COMMENT '标签的描述',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of wg_article
-- ----------------------------
INSERT INTO `wg_article` VALUES ('1', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:03:15', '2016-04-15 21:15:13', null, null);
INSERT INTO `wg_article` VALUES ('2', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:03:32', '2016-04-15 21:15:16', null, null);
INSERT INTO `wg_article` VALUES ('3', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:09', '2016-04-15 21:15:18', null, null);
INSERT INTO `wg_article` VALUES ('4', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:12', '2016-04-15 21:15:22', null, null);
INSERT INTO `wg_article` VALUES ('5', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:15', '2016-04-15 21:15:26', null, null);
INSERT INTO `wg_article` VALUES ('6', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:34', '2016-04-15 21:15:29', null, null);
INSERT INTO `wg_article` VALUES ('7', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:37', '2016-04-15 21:15:32', null, null);
INSERT INTO `wg_article` VALUES ('8', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:41', '2016-04-15 21:15:36', null, null);
INSERT INTO `wg_article` VALUES ('9', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:44', '2016-04-15 21:15:40', null, null);
INSERT INTO `wg_article` VALUES ('10', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:46', '2016-04-15 21:15:43', null, null);
INSERT INTO `wg_article` VALUES ('11', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:48', '2016-04-15 21:15:46', null, null);
INSERT INTO `wg_article` VALUES ('12', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:50', '2016-04-15 21:15:49', null, null);
INSERT INTO `wg_article` VALUES ('13', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:04:53', '2016-04-15 21:15:53', null, null);
INSERT INTO `wg_article` VALUES ('14', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:05:02', '2016-04-15 21:15:55', null, null);
INSERT INTO `wg_article` VALUES ('15', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:05:04', '2016-04-15 21:15:57', null, null);
INSERT INTO `wg_article` VALUES ('16', 'Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-15 21:05:06', '2016-04-15 21:16:01', null, null);
INSERT INTO `wg_article` VALUES ('17', '17Developing Instrumentation Techniques for Speech Production Studies', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology. Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-16 15:17:46', '2016-04-15 21:16:04', null, null);

-- ----------------------------
-- Table structure for wg_images
-- ----------------------------
DROP TABLE IF EXISTS `wg_images`;
CREATE TABLE `wg_images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `random_name` varchar(50) NOT NULL,
  `origin_name` varchar(50) DEFAULT NULL,
  `path` varchar(50) NOT NULL,
  `label` int(3) DEFAULT NULL,
  `label_description` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of wg_images
-- ----------------------------
INSERT INTO `wg_images` VALUES ('1', '570cd54944815.png', '1.png', '', null, null);
INSERT INTO `wg_images` VALUES ('2', '570cd58fe334e.png', '1.png', '', null, null);
INSERT INTO `wg_images` VALUES ('3', '570cdab133741.png', '1.png', '', null, null);
INSERT INTO `wg_images` VALUES ('4', '570cdab8c31d3.png', '2.png', '', null, null);
INSERT INTO `wg_images` VALUES ('5', '570cdc66b8c2b.jpg', 'Chrysanthemum.jpg', '', null, null);
INSERT INTO `wg_images` VALUES ('6', '5711e54474300.jpg', 'Penguins.jpg', '', null, null);
INSERT INTO `wg_images` VALUES ('7', '5711f5968312c.jpg', 'Koala.jpg', '', null, null);
INSERT INTO `wg_images` VALUES ('8', '5711f771d7d60.jpg', 'Penguins.jpg', '', null, null);

-- ----------------------------
-- Table structure for wg_information
-- ----------------------------
DROP TABLE IF EXISTS `wg_information`;
CREATE TABLE `wg_information` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `category` int(5) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `content` text NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `update-at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of wg_information
-- ----------------------------
INSERT INTO `wg_information` VALUES ('1', '1', 'personal_information', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-14 23:08:54', '2016-04-16 16:27:34');
INSERT INTO `wg_information` VALUES ('2', '2', 'research_information', '&lt;p&gt;- Multisensory Instrumentation for exploring speech production mechanisms - Magnetic resonance imaging (MRI) for observing speech production processes - Modeling of speech articulation and Chinese phonetics (jointly with Prof. Dang and Prof. Wei) - Graduate Course guidance for next-generation experts for speech research&lt;/p&gt;\r\n', '2016-04-14 23:14:22', '2016-04-16 16:27:38');
INSERT INTO `wg_information` VALUES ('3', '3', 'experience_information', '&lt;p&gt;1985.4 Doctor of Medical Sciences (D.M.Sc.),University of Tokyo, Faculty of Medicine 1976.3 Bachelor of Medicine (B.M.), Nara Medical University, Medical School 1970.4 - 1976.3 Nara Medical University, Medical School (Japan) 1965.4 - 1968.3 Tokyo Metropolitan Kudan High School (Japan)&lt;/p&gt;\r\n', '2016-04-14 23:14:26', '2016-04-16 16:27:44');
INSERT INTO `wg_information` VALUES ('4', '4', 'honors_information', '&lt;p&gt;Qualifications 1975.5 Medical Doctor (M.D.), Ministry of Health and Welfare, Japan Honors - 2006.12 7th Willard R. Zemlin Lecture from Allyn &amp;amp; Bacon &amp;amp; ASHA Division 5, U.S.A. - 1970.4 - 1976.3 Nara Medical University, Medical School (Japan) - 2012.5 Quintana Research Award 2012 from the Voice Foundation, U.S.A.&lt;/p&gt;\r\n', '2016-04-14 23:14:30', '2016-04-16 16:27:49');
INSERT INTO `wg_information` VALUES ('5', '5', 'achievements_information', '&lt;p&gt;Will has over eight years experience in providing informatics,analytical and methodological solutions towards biomedical science. He currently holds a Professorship in Bioinformatics, Tianjin University, one of the top 25 universities in China, and is now pursuing advanced training in Harvard University. He has advised and collaborated on a wide variety of projects, including international work on biological network analysis, proteomics and genomics problems. Will has a head for unconventional thinking and has used it, on several occasions for solving fundamental analytical roadblocks in modern biology.&lt;/p&gt;\r\n', '2016-04-14 23:18:32', '2016-04-16 16:27:54');
INSERT INTO `wg_information` VALUES ('6', '6', 'basic_information', '&lt;p&gt;Speaking is a unique capacity of humans, which involves physiological and acoustic mechanisms of a human body across many stages of linguistic, neural sensorimotor, peripheral bio mechanic, and aero-acoustic systems. Studies of speech production aim at exploring those mechanisms by interdisciplinary approach combining phonetics, physiology, engineering, and medicine.&lt;/p&gt;\r\n', '2016-04-15 20:21:40', '2016-04-16 16:28:42');
INSERT INTO `wg_information` VALUES ('7', '7', 'courses_taugh', '&lt;p&gt;Speaking is a unique capacity of humans, which involves physiological and acoustic mechanisms of a human body across many stages of linguistic, neural sensorimotor, peripheral bio mechanic, and aero-acoustic systems. Studies of speech production aim at exploring those mechanisms by interdisciplinary approach combining phonetics, physiology, engineering, and medicine.&lt;/p&gt;\r\n', '2016-04-16 15:30:11', '2016-04-16 15:32:52');
INSERT INTO `wg_information` VALUES ('8', '8', 'journal_papers', '&lt;p&gt;- Hyon, S., Dang, J., Feng, H., Wang, H., &amp;amp; Honda, K. (2014) Detection of speaker individual information using a phoneme effect suppression method. Speech Communication, 57: 87-100. - Vaissiere, J., Honda, K., Amelot, A., Maeda, S., &amp;amp; Crevier-Buchman, L. (2010) Multisensor platform for speech physiology research in a phonetics laboratory. Journal of the Phonetic Society of Japan, 14: 65-77.&lt;/p&gt;\r\n', '2016-04-16 15:30:26', '2016-04-16 15:32:48');
INSERT INTO `wg_information` VALUES ('9', '9', 'technical_papers', '&lt;p&gt;- Fujimura, O., Honda, K., Kawahara, H., Konparu, Y., Morise, M., &amp;amp; Williams, J.C. (2009) Noh voice quality. Logopedics Phiniatrics and Vocology, 4: 1-14. - Boe, L-J., Heim, J-L., Honda, K., &amp;amp; Maeda, S. (2002) The potential Neandertal vowel space was as large as that of modern humans. Journal of Phonetics, 30, 465-484.&lt;/p&gt;\r\n', '2016-04-16 15:33:30', '2016-04-16 15:33:38');

-- ----------------------------
-- Table structure for wg_user
-- ----------------------------
DROP TABLE IF EXISTS `wg_user`;
CREATE TABLE `wg_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `title` varchar(50) NOT NULL,
  `address` varchar(50) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `email` varchar(50) NOT NULL,
  `remark` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `password` varchar(50) NOT NULL DEFAULT '123456',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of wg_user
-- ----------------------------
INSERT INTO `wg_user` VALUES ('1', '12', '12', '12', '12', '120406191@qq.com', null, '2016-04-04 15:30:09', '2016-04-16 16:39:49', '12');
